[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npx prisma generate --schema=libs/database/src/schema.prisma",
  "npx nest build"
]

[start]
cmd = "npm run ${START_SCRIPT:-start:prod}"
