[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity/',
    'forge-std/=lib/forge-std/src/'
]
# Allow deployment JSON writes
fs_permissions = [{ access = "read-write", path = "./" }]

# Contract verification settings (for Sourcify & Blockscout)
metadata = true
metadata_hash = "none"
use_literal_content = true

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
base_sepolia = "https://sepolia.base.org"
